### ISSUE TITLE
Cannot import name 'DependantBase' from 'di.api.dependencies'

### ISSUE THREAD

**Issue by dantownsend** [adriangb/xpresso#111]
I'm getting this error when running Xpresso:

```python
from di.api.dependencies import DependantBase
ImportError: cannot import name 'DependantBase' from 'di.api.dependencies'
```

I see you renamed something in di recently. How about putting something like this for backwards compatibility:

```
DependantBase = DependentBase
```

**Comment by adriangb** [comment]
I think I’ll just bump the minimum di version here. I guess I should really just pin it…

**Comment by dantownsend** [comment]
Yeah, I just came across this issue because in the Piccolo integration tests we're using `xpresso==0.43.0` because FastAPI annoyingly version pins to older Starlette versions, so we can't resolve our dependencies with the latest xpresso.

I can try version pinning to an older di version for now.

**Comment by dantownsend** [comment]
I have a solution - version pinned di. Will close, thanks.

**Comment by adriangb** [comment]
Thanks. I still need to do something here so that this doesn't happen again, it's not the first time...

**Comment by adriangb** [comment]
FYI I released a new version with a fix and pined `di` version. Again terribly sorry for breaking your builds.

**Comment by dantownsend** [comment]
Cool, no worries.
