### ISSUE TITLE
feat: allow setting root_path

### ISSUE THREAD

**Issue by adriangb** [adriangb/xpresso#37]
How would this interact with OpenAPI? With routing? Probably worth referring to FastAPI

**Comment by sm-Fifteen** [comment]
FastAPI adds the root_path in the OpenAPI server list since tiangolo/fastapi#1596, making it so all paths in the documentation [are to be understood as being relative to that URL](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#oasServers).

**Comment by adriangb** [comment]
Yup I think we'll want to do the same thing here, thank you for linking the original discussion
